
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.smband.soap.model;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T10:30:27.567+09:00
 * Generated source version: 2.7.18
 * 
 */

@javax.jws.WebService(
                      serviceName = "TicketAgentService",
                      portName = "TicketAgentSoap",
                      targetNamespace = "http://example.org/TicketAgent.wsdl11",
                      wsdlLocation = "file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/work/ticketagent.wsdl",
                      endpointInterface = "com.smband.soap.model.TicketAgent")
                      
public class TicketAgentImpl implements TicketAgent {

    private static final Logger LOG = Logger.getLogger(TicketAgentImpl.class.getName());

    /* (non-Javadoc)
     * @see com.smband.soap.model.TicketAgent#listFlights(com.smband.soap.model.TListFlights  body )*
     */
    public com.smband.soap.model.TFlightsResponse listFlights(TListFlights body) { 
        LOG.info("Executing operation listFlights");
        System.out.println(body);
        try {
            com.smband.soap.model.TFlightsResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
