package com.smband.soap.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T10:30:27.577+09:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "TicketAgentService", 
                  wsdlLocation = "file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/work/ticketagent.wsdl",
                  targetNamespace = "http://example.org/TicketAgent.wsdl11") 
public class TicketAgentService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://example.org/TicketAgent.wsdl11", "TicketAgentService");
    public final static QName TicketAgentSoap = new QName("http://example.org/TicketAgent.wsdl11", "TicketAgentSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/work/ticketagent.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TicketAgentService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/work/ticketagent.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TicketAgentService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TicketAgentService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TicketAgentService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TicketAgentService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TicketAgentService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public TicketAgentService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns TicketAgent
     */
    @WebEndpoint(name = "TicketAgentSoap")
    public TicketAgent getTicketAgentSoap() {
        return super.getPort(TicketAgentSoap, TicketAgent.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TicketAgent
     */
    @WebEndpoint(name = "TicketAgentSoap")
    public TicketAgent getTicketAgentSoap(WebServiceFeature... features) {
        return super.getPort(TicketAgentSoap, TicketAgent.class, features);
    }

}
