package com.smband.soap.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T10:30:27.573+09:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://example.org/TicketAgent.wsdl11", name = "TicketAgent")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface TicketAgent {

    @WebMethod
    @WebResult(name = "listFlightsResponse", targetNamespace = "http://example.org/TicketAgent.xsd", partName = "body")
    public TFlightsResponse listFlights(
        @WebParam(partName = "body", name = "listFlightsRequest", targetNamespace = "http://example.org/TicketAgent.xsd")
        TListFlights body
    );
}
