
package com.smband.soap.model;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T10:30:27.521+09:00
 * Generated source version: 2.7.18
 * 
 */
public final class TicketAgent_TicketAgentSoap_Client {

    private static final QName SERVICE_NAME = new QName("http://example.org/TicketAgent.wsdl11", "TicketAgentService");

    private TicketAgent_TicketAgentSoap_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TicketAgentService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        TicketAgentService ss = new TicketAgentService(wsdlURL, SERVICE_NAME);
        TicketAgent port = ss.getTicketAgentSoap();  
        
        {
        System.out.println("Invoking listFlights...");
        com.smband.soap.model.TListFlights _listFlights_body = null;
        com.smband.soap.model.TFlightsResponse _listFlights__return = port.listFlights(_listFlights_body);
        System.out.println("listFlights.result=" + _listFlights__return);


        }

        System.exit(0);
    }

}
