package com.smband.soap.model;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T11:09:33.857+09:00
 * Generated source version: 2.7.18
 * 
 */
@WebServiceClient(name = "countriesPortService", 
                  wsdlLocation = "file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/src/main/resources/countries.wsdl",
                  targetNamespace = "http://www.smband.com/countries") 
public class CountriesPortService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.smband.com/countries", "countriesPortService");
    public final static QName CountriesService = new QName("http://www.smband.com/countries", "countriesService");
    static {
        URL url = null;
        try {
            url = new URL("file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/src/main/resources/countries.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(CountriesPortService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/D:/javaProject/workspace-sts4-test2/soap-svc-maven/src/main/resources/countries.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public CountriesPortService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public CountriesPortService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CountriesPortService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CountriesPortService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CountriesPortService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    //This constructor requires JAX-WS API 2.2. You will need to endorse the 2.2
    //API jar or re-run wsdl2java with "-frontend jaxws21" to generate JAX-WS 2.1
    //compliant code instead.
    public CountriesPortService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     *     returns CountriesPort
     */
    @WebEndpoint(name = "countriesService")
    public CountriesPort getCountriesService() {
        return super.getPort(CountriesService, CountriesPort.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CountriesPort
     */
    @WebEndpoint(name = "countriesService")
    public CountriesPort getCountriesService(WebServiceFeature... features) {
        return super.getPort(CountriesService, CountriesPort.class, features);
    }

}
