
package com.smband.soap.model;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T11:09:33.794+09:00
 * Generated source version: 2.7.18
 * 
 */
public final class CountriesPort_CountriesService_Client {

    private static final QName SERVICE_NAME = new QName("http://www.smband.com/countries", "countriesPortService");

    private CountriesPort_CountriesService_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = CountriesPortService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        CountriesPortService ss = new CountriesPortService(wsdlURL, SERVICE_NAME);
        CountriesPort port = ss.getCountriesService();  
        
        {
        System.out.println("Invoking findCountry...");
        com.smband.soap.model.GetCountryRequest _findCountry_countryRequest = null;
        com.smband.soap.model.CommonHeader _findCountry_commonHeaderVal = null;
        javax.xml.ws.Holder<com.smband.soap.model.CommonHeader> _findCountry_commonHeader = new javax.xml.ws.Holder<com.smband.soap.model.CommonHeader>(_findCountry_commonHeaderVal);
        com.smband.soap.model.GetCountryResponse _findCountry__return = port.findCountry(_findCountry_countryRequest, _findCountry_commonHeader);
        System.out.println("findCountry.result=" + _findCountry__return);

        System.out.println("findCountry._findCountry_commonHeader=" + _findCountry_commonHeader.value);

        }

        System.exit(0);
    }

}
