package com.smband.soap.model;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.18
 * 2023-04-23T11:09:33.853+09:00
 * Generated source version: 2.7.18
 * 
 */
@WebService(targetNamespace = "http://www.smband.com/countries", name = "CountriesPort")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface CountriesPort {

    @WebMethod(action = "http://www.smband.com/countries/country")
    @WebResult(name = "getCountryResponse", targetNamespace = "http://www.smband.com/countries", partName = "countryResponse")
    public GetCountryResponse findCountry(
        @WebParam(partName = "countryRequest", name = "getCountryRequest", targetNamespace = "http://www.smband.com/countries")
        GetCountryRequest countryRequest,
        @WebParam(partName = "commonHeader", mode = WebParam.Mode.INOUT, name = "commonHeader", targetNamespace = "http://www.smband.com/countries", header = true)
        javax.xml.ws.Holder<CommonHeader> commonHeader
    );
}
